[package]
name = "freetype-sys"
version = "2.4.11"
authors = ["The FreeType Team"]
links = "freetype"
build = "build.rs"

[lib]
name = "freetype_sys"
path = "lib.rs"

[build-dependencies]
pkg-config = "0.3"
